FROM golang:1.13.4-alpine3.10 As builder
RUN apk update && apk add --no-cache git

WORKDIR /go/src/giskard/

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .


RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o app .

FROM alpine:3.7

WORKDIR /app/
COPY --from=builder /go/src/giskard/app .
COPY /config /app/config
COPY /jwt /app/jwt

ENTRYPOINT ["./app"]